tokenizer:
  path: "/data/.cache/models/deepseek-ai/DeepSeek-V4-Flash"
  model_type: "deepseek4"
dataset:
  name:  "/data/.cache/hub/datasets/AI-ModelScope/ShareGPT-Chinese-English-90k/sharegpt_jsonl"
  output_path: "datasets/ShareGPT-Chinese-English-90k/preprocessed-deepseek-v4/"
