model:
  path: "/data/.cache/models/deepseek-ai/DeepSeek-V4-Flash"
  dtype: "bfloat16"
  attn_implementation: "flash_attention_2"
  output_path: "Amatrices/deepseek-v4_n_samples_2048_think"
  output_format: "hf"
  save_model: False
  model_type: "deepseek-v4"

calibration:
  dataset_path: "datasets/ShareGPT-Chinese-English-90k/preprocessed-deepseek-v4/" #"datasets/OpenHermes-2.5/preprocessed-Qwen3-8B"
  n_samples: 2048
  seed: 42
  batch_size: 1
  sequence_filter: 3072
