model:
  path: "output/norm_ratio/Llama-3.1-8B-Instruct/norm_ratio_8_removed/"
  output_format: "hf"
  save_model: False
  dtype: "bfloat16"
teacher_model:
  path: "models/Llama-3.1-8B-Instruct/"
  dtype: "bfloat16"

dataset:
  path:  "datasets/OpenHermes-2.5/preprocessed-Llama-3.1-8B-Instruct/"
  test_size: 0.01
  seed: 42
  shuffle: True

training:
  output_dir: "output"

  # Training duration - online healing for larger model
  max_steps: 10000
  num_train_epochs: 1  # Use max_steps instead

  # Batch size configuration for 8B model
  per_device_train_batch_size: 16  # Reduced for larger model
  per_device_eval_batch_size: 16
  gradient_accumulation_steps: 1  #  # Maintain effective batch size =  32* 16 * num_gpus

  # Learning rate and optimization - conservative for 8B model
  learning_rate: 2.0e-5 # changed fro  1e-04to 2.0e-5
  weight_decay: 1.0e-4
  warmup_steps: 100  # 10% of max_steps
  max_grad_norm: 1.0
  lr_scheduler_type: "cosine"
  max_length: 1024
  # Logging and checkpointing
  logging_steps: 10
  save_steps: 2000 # changed from 2000 to 10000
  eval_steps: 1000 #changed from 1000 to 5000
  packing: False
  #deepspeed: "src/finetuning/configs/ds_config.json"

