model:
  path: "/data2/work/Block_removal_through_constrained_binary_optimization/Amatrices/Qwen3-8B_n_samples_2048_think/energies_del8/compressed_model_state_1"
  dtype: "bfloat16"
  attn_implementation: "flash_attention_2"
  output_format: "hf"
  save_model: False
teacher_model:
  path: "/data/.cache/models/Qwen/Qwen3-8B"
  dtype: "bfloat16"

dataset:
  path:  "/data/work/Block_removal_through_constrained_binary_optimization/datasets/ShareGPT-Chinese-English-90k/preprocessed-Qwen3-8B"
  test_size: 0.005
  seed: 42
  shuffle: True

training:
  output_dir: "output"

  # Training duration - online healing for larger model
  max_steps: 10000
  num_train_epochs: 1  # Use max_steps instead

  # Batch size configuration for 8B model
  per_device_train_batch_size: 1  # Reduced for larger model
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 2  # Maintain effective batch size =  32* 16 * num_gpus

  # Learning rate and optimization - conservative for 8B model
  learning_rate: 1.0e-4
  weight_decay: 1.0e-4
  warmup_steps: 100  # 10% of max_steps
  max_grad_norm: 1.0
  lr_scheduler_type: "cosine"
  max_length: 1024
  # Logging and checkpointing
  logging_steps: 10
  save_steps: 100 # 每100步保存checkpoint，减少中断后进度丢失
  eval_steps: 100 #changed from 1000 to 5000
  packing: False
  resume_from_checkpoint: null  # null=自动检测最新checkpoint, 或指定路径
  #deepspeed: "src/
  #deepspeed: "src/

